runtime: nodejs18
service: default
env: standard
handlers:
  - url: /.*
    script: server.js
    secure: always
env_variables:
  NODE_ENV: production
  NODE_OPTIONS: --openssl-legacy-provider
  ACCESS_CONTROL: https://comiccruncher.com
  PORT: 8080
