version: "3.1"
services:
  pm2:
    restart: always
    image: keymetrics/pm2:10-alpine
    volumes:
      - .:/srv/www/comiccruncher
    working_dir: /srv/www/comiccruncher
    ports:
      - "3000:3000"
    command: pm2-runtime start ./deploy/uploads/pm2/config.json
    environment:
      NODE_ENV: development
  nginx:
    restart: always
    image: nginx:1.15-alpine
    links:
      - pm2
    ports:
      - "8002:80"
    volumes:
      - ./deploy/uploads/nginx:/etc/nginx
