version: "3.2"
services:
  comiccruncher:
    image: node:18-alpine
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - "NODE_OPTIONS=--openssl-legacy-provider"
      - "NODE_ENV=${CC_NODE_ENV:-development}"
    command: yarn dev
