version: "3.1"
services:
  comiccruncher:
    image: node:11.4-alpine
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - "NODE_ENV=${CC_NODE_ENV:-development}"
    command: yarn dev
