version: "3.2"
services:
  comiccruncher:
    image: node:11.4-alpine
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - "NODE_ENV=${CC_NODE_ENV:-development}"
    command: yarn dev
  production_test:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - "NODE_ENV=${CC_NODE_ENV:-production}"
