version: "3.2"
services:
  letsencrypt:
    container_name: frontend_letsencrypt
    restart: always
    image: linuxserver/letsencrypt
    environment:
      - EMAIL=aimee@aimeelaplant.com
      - URL=comiccruncher.com
      - SUBDOMAINS=www
      - TZ=America/NewYork
      - VALIDATION=dns
      - DNSPLUGIN=route53
      - PUID=1001
      - PGID=1001
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
    volumes:
      - ./config:/config
      - letsencrypt:/etc/letsencrypt
  nginx:
    container_name: frontend_nginx
    restart: always
    image: nginx:1.15-alpine
    depends_on:
      - letsencrypt
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - letsencrypt:/etc/letsencrypt
  datadog:
    container_name: datadog
    restart: always
    image: datadog/agent:6.8.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      DD_API_KEY: "${CC_DD_API_KEY}"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_AC_EXCLUDE: "name:datadog"
      DD_ENABLE_PAYLOADS_EVENTS: "false"
      DD_ENABLE_PAYLOADS_SERIES: "false"
      DD_ENABLE_PAYLOADS_SERVICE_CHECKS: "false"
      DD_ENABLE_PAYLOADS_SKETCHES: "false"
volumes:
  letsencrypt:
