version: "3.1"
services:
  pm2:
    restart: always
    image: comiccruncher/frontend:test
  nginx:
    restart: always
    image: nginx:1.15-alpine
    links:
      - pm2
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
    links:
      - pm2
    depends_on:
      - pm2
  log:
    restart: always
    image: gliderlabs/logspout
    command: syslog+tls://${CC_LOG_LOCATION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
