version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.3.0
workflows:
  install_deps_build_and_deploy:
    jobs:
      - install_deps:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build_publish_deploy:
          context: GCP
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  install_deps:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys: 
            - node_modules-{{ checksum "yarn.lock" }}
            - node_modules
      - run:
          name: Install dependencies.
          command: make docker-yarn-install-circleci
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
  build_publish_deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
            - node_modules
      - add_ssh_keys:
          fingerprints:
            - "c8:9c:22:02:8e:c5:4b:8e:3b:80:70:a1:3d:59:cf:ca"
            - "4f:14:ed:5a:08:98:d9:79:07:58:bd:23:5a:45:07:e2"
            - "4d:5f:1b:f6:81:d2:89:21:cf:ed:2f:29:eb:4a:1c:d3"
      - run:
          name: Build the files.
          command: make docker-yarn-build
      - run:
          name: Upload the files.
          command: make docker-upload-s3
      - gcp-cli/initialize
      - run:
          name: Deploy the app to GCP.
          command: gcloud app deploy --verbosity=debug --stop-previous-version --quiet
