version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.3.0
workflows:
  install_deps_build_and_deploy:
    jobs:
      - install_deps:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build_publish_deploy:
          context: GCP
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  install_deps:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys: 
            - prod-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install production dependencies.
          command: make install-production
      - save_cache:
          key: prod-deps-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - restore_cache:
          keys: 
            - deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies.
          command: make install
      - run:
          name: Build app.
          command: make build
      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
     - save_cache:
        key: build-{{ .CIRCLE_WORKFLOW_ID }}
        paths:
          - "build"
  build_publish_deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-{{ .CIRCLE_WORKFLOW_ID }}
      - run:
          name: Upload the files.
          command: make s3
      - gcp-cli/initialize
      - run:
          name: Show gcloud version
          command: gcloud version
      - run:
          name: Deploy the app to GCP.
          command: gcloud app deploy --stop-previous-version --quiet
