version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.3.0
workflows:
  install_deps_build_and_deploy:
    jobs:
      - install_deps:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build_publish_deploy:
          context: GCP
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  install_deps:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys: 
            - node_modules-{{ checksum "yarn.lock" }}
            - node_modules
      - run:
          name: Install dependencies.
          command: make docker-yarn-install-circleci
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
  build_publish_deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
            - node_modules
      - run:
          name: Build the files.
          command: make docker-yarn-build
      - run:
          name: Upload the files.
          command: make docker-upload-s3
      - gcp-cli/initialize
      - run:
          name: Show gcloud version
          command: gcloud version
      - run:
          name: Deploy the app to GCP.
          command: gcloud app deploy --stop-previous-version --quiet
