version: 2
workflows:
  version: 2
  install_deps_build_and_deploy:
    jobs:
      - install_deps:
          filters:
            branches:
              only: /.*/
      - build_and_deploy:
          requires:
            - install_deps
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  install_deps:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - restore_cache:
          keys: 
            - node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies.
          command: yarn install
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
  build_and_deploy:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - restore_cache:
          keys: 
            - node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Build the application.
          command: yarn build
      - run:
          name: Upload assets to S3.
          command: make docker-upload-s3 > /dev/null
      - run:
          name: Login to docker.
          command: docker login -u $CC_DOCKER_USER -p $CC_DOCKER_PASS > /dev/null
      - run:
          name: Build the docker image.
          command: make docker-build-pm2
      - run:
          name: Push the docker image.
          command: make docker-push-pm2
      - add_ssh_keys:
          fingerprints:
            - "c8:9c:22:02:8e:c5:4b:8e:3b:80:70:a1:3d:59:cf:ca"
            - "4f:14:ed:5a:08:98:d9:79:07:58:bd:23:5a:45:07:e2"
            - "4d:5f:1b:f6:81:d2:89:21:cf:ed:2f:29:eb:4a:1c:d3"
      - run:
          name: Deploy pm2 applications.
          command: make remote-deploy-pm2
      - run:
          name: Deploy the nginx application!
          command: make docker-reload-nginx
