version: "3.4"
services:
  certbot:
    restart: always
    container_name: certbot
    image: certbot/dns-route53:v0.30.0
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;"
    environment:
       AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
       AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    volumes:
      - letsencrypt:/etc/letsencrypt
    logging:
      options:
        max-size: "25M"
        max-file: "3"
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx:/var/log/nginx
      - letsencrypt:/etc/letsencrypt
    networks:
      log:
        ipv4_address: 172.25.0.101
    logging:
      options:
        max-size: "25M"
        max-file: "3"
    environment:
      HOSTNAME: "${HOSTNAME}"
  telegraf:
    container_name: telegraf
    restart: always
    depends_on:
      - nginx
    image: telegraf:1.9-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - type: bind
        source: /run/utmp
        target: /host/var/run/utmp
    networks:
      log:
        ipv4_address: 172.25.0.102
    logging:
      options:
        max-size: "25M"
        max-file: "3"
    environment:
      HOSTNAME: "${HOSTNAME}"
      HOST_VAR: "/host/var"
  filebeat:
    command: ["--strict.perms=false"]
    restart: always
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:6.5.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - filebeat:/usr/share/filebeat/data
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - nginx:/var/log/nginx
    logging:
      options:
        max-size: "25M"
        max-file: "3"
    environment:
      HOSTNAME: "${HOSTNAME}"
      ELASTIC_HOST: "10.136.103.144:9200"
      ELASTIC_USER: "${CC_ELASTIC_USER}"
      ELASTIC_PASSWORD: "${CC_ELASTIC_PASSWORD}"
      KIBANA_HOST: "${CC_KIBANA_HOST}"
      KIBANA_USER: "${CC_KIBANA_USER}"
      KIBANA_PASSWORD: "${CC_KIBANA_PASSWORD}"
    labels:
      - "co.elastic.logs/disable=true"
networks:
  log:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
volumes:
  letsencrypt:
  filebeat:
  nginx:
